### ISSUE TITLE
Support for large-v2

### ISSUE THREAD

**Issue by Mario03482** [Saik0s/Whisperboard#10]
Will you add the support for large-v2? Maybe on the new iPhones the large model can run without any issue?

**Comment by Saik0s** [comment]
Yes! It will already in the repository and will be in a new update.

**Comment by Mario03482** [comment]
Is there a deadline?

**Comment by Saik0s** [comment]
Submitted new version to App Store, waiting for review. I expect it to be available today - tomorrow.

**Comment by Mario03482** [comment]
Another question: I wanted to use this app to transcribe long audio file(~2h) using the large-v2, do you think it is possible to do it without having any bug/crash?
iPhone 14 pro max

**Comment by Saik0s** [comment]
A new version is now available on the App Store!

I haven't tested large files yet, so I don't anticipate any bugs, except for the time it takes to transcribe audio. I believe that for such lengthy files, I need to implement a resuming mechanism so users can continue transcription after exiting the app. I've included live progress updates for the transcription, which should help users understand the current stage. I plan to add some benchmarks later.

**Comment by Mario03482** [comment]
What is you to do list now? And the priorities at the moment?

**Comment by Saik0s** [comment]
I have several things that I want to focus:
- fixing small bugs here and there
- transcription in background
- estimation of how much time is left for transcription
- add files to the queue for transcription
- resumable transcription in case app was killed

**Comment by coder543** [comment]
I see a "large" model in the app, but there's no indication of whether it is Large-V1 or Large-V2. I tried glancing through the source code here, and I'm still not sure. Since "V2" doesn't appear anywhere [in here](https://github.com/Saik0s/Whisperboard/blob/main/App/Sources/App/Entities/VoiceModel.swift#L27), I'm wondering if it might still be V1.

Either way, this seems like a really neat app!

**Comment by Saik0s** [comment]
It is V2, I decided to not include V1. Will add this to description of the model.
