### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by seren** [Saik0s/Whisperboard#12]
I was playing around with this in Xcode and then realized it’s live in the App Store. Awesome!

My three initial findings are (and I can file separate issues if preferable, and provide screen recordings):

1. The app crashes if I hit “transcribe” after recording something. When I re-open the app and hit transcribe, then it succeeds.
2. The transcription doesn’t always seem to be accurate. For a simple two-sentence recording, I had to re-transcribe it three times before it picked up the first and last five seconds.
3. There doesn’t currently seem to be any way to delete models that are not needed, but taking up space.

**Comment by coder543** [comment]
I just downloaded this app, and it does seem prone to crashing. I've also noticed that downloading models never actually completes -- it gets stuck close to 100%. If I restart the app, those models did succeed in downloading, even though the UI was unaware of it.

It would also be nice if a transcription had a visual element somewhere that showed _which_ model it was transcribed with, and maybe even how long it took to transcribe.

**Comment by seren** [comment]
I found that issue as well, where the UI never completes the download progress. Tapping a different model, and then tapping on the downloaded/ing one jogs the UI into showing it as completed, without having to quit the app.

**Comment by Saik0s** [comment]
Hey, thanks for letting me know about these issues. I've actually noticed them too, but haven't had a chance to check them out yet. I'll try to get them fixed up today or tomorrow and put out a new version.

Oh, and if you want to delete a downloaded model, just long-press on it and choose "delete" from the menu. I know it's not the most obvious spot for it, so I'll see if there's a better way to make it more obvious.

**Comment by seren** [comment]
Awesome, thanks! I tried out the latest release and it’s definitely less crashy. I found some other bugs, but will open a new issue for them.
