### ISSUE TITLE
M2 iPad

### ISSUE THREAD

**Issue by Mario03482** [Saik0s/Whisperboard#13]
Did someone try this app on an iPad with m2? How does it perform?

**Comment by Marcio2536** [comment]
It absolutely sucks in terms of the UI. All settings and configuration interface was messed up. The app will need a real fix for it to be usable on iPad.

**Comment by Saik0s** [comment]
Sorry iPad experience sucks, should have disabled iPad support until I fix it. I am fixing now and will make a new version this week.

**Comment by Saik0s** [comment]
Finally it is done! Latest release contains fixes for iPad experience, everything should be working now.

**Comment by Mario03482** [comment]
And how does it perform?

**Comment by Saik0s** [comment]
@Mario03482 Just tried to transcribe 3 min recording using large-v2 model and it took around 10 minutes.

**Comment by Mario03482** [comment]
why is it so slow?

**Comment by coder543** [comment]
The large model is huge. Obviously a smaller model would be tremendously faster, and even the “tiny” model is arguably better than Apple’s current voice to text system (which may change with iOS 17, but I don’t know).
