### ISSUE TITLE
Ability to suspend or cancel transcription

### ISSUE THREAD

**Issue by tylerbenson** [Saik0s/Whisperboard#19]
Transcription can take a long time and lots of resources. Would be nice to be able to pause or cancel.

Other ideas to consider:
- Compare/view retranscription history
- Add metadata showing which model was used for transcription.

Great app! Really appreciate the work you've put into it.

**Comment by Saik0s** [comment]
Hello @tylerbenson, I have included the option to cancel transcription. It will be accessible in the upcoming release, either this week or next week. Thank you for your other suggestions. I would like to add them, but it will require some time. At least, displaying the used model is on my to-do list.
