### ISSUE TITLE
update to whisper v3

### ISSUE THREAD

**Issue by rawwerks** [Saik0s/Whisperboard#22]
openai pushed v3 a few hours ago: https://github.com/openai/whisper

**Comment by coder543** [comment]
I am curious how well large-v3 works for other people… I did a quick test earlier using the reference implementation from OpenAI, and I found the results to be worse than large-v2… the new model had a tendency to repeat the same multi-second transcript several times in the output, with each one being a fraction of a second. It was kind of weird. I definitely need to test it more, and it would be great to have it as an option in the app.

**Comment by rawwerks** [comment]
I was seeing this before too: https://github.com/Saik0s/Whisperboard/issues/17

@Saik0s - is this app still an active project for you?

**Comment by Saik0s** [comment]
Yes, I am planning to update it this week and will try to include version 3 in the update.
