### ISSUE TITLE
A huge amount of dependencies downloaded by the 'make' command

### ISSUE THREAD

**Issue by shawnchain** [Saik0s/Whisperboard#23]
This might not be an issue to this project but indeed it requires a lots of time and spaces to download. Would be really appreciated if the dependencies could be optimized. Thanks!

**Comment by Saik0s** [comment]
Hi @shawnchain, the app is 100MB after install, where 75MB is taken by the bundled tiny model. Dependencies are minimal compared to this, so I will mark this issue as resolved.

**Comment by shawnchain** [comment]
@Saik0s Thanks for the quick reply!
I noticed that folder size of 'Tuist/Dependencies' is about 1.8G and especially, the dependency 'purchases-ios-92046cd5' occupies 1.1G disk space. 
I believe it's the 3rd party library issue. I'm a C programmer and I'm really astonished by the swift dependency management tool.
Anyway, thank you for this great project!
