### ISSUE TITLE
Make is not running. "No such file or directory: '../.env'"

### ISSUE THREAD

**Issue by Raidansz** [Saik0s/Whisperboard#28]
This is what I get when I run "make". 

**MacBook-Pro Whisperboard % make**
[Errno 2] No such file or directory: '../.env'
Failed to read .env file. Using default values.
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Swift Package Manager dependencies.
error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
    
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
make: *** [project_file] Error 1

**Comment by Saik0s** [comment]
Hi @Raidansz , ensure you have a functioning Xcode installation. If confirmed, try this command `sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer`

**Comment by Raidansz** [comment]
Hi @Saik0s , it worked! Thank you! I was able to run the app on an iPhone, not a simulator. However, unfortunately, the transcription does not work. I have attached a screenshot so you can see the error message.
![IMG_4189](https://github.com/Saik0s/Whisperboard/assets/92235772/092180fe-bd4c-4bd0-ad76-4fb81a5cd050)

**Comment by Saik0s** [comment]
I think the issue should be solver by now, feel free to reopen it if it is still exist.
