### ISSUE TITLE
why my download are not access? 

### ISSUE THREAD

**Issue by immotal** [Saik0s/Whisperboard#3]
![image](https://user-images.githubusercontent.com/40708234/224712966-2b5e202c-ffb6-49ab-a40f-17f55c11a4b7.png)
 i do not know why , could you please tell me 
iphone 13 pro

**Comment by Saik0s** [comment]
Hi @immotal. Thanks for reporting this issue, I will look into it. 

Is it a fresh install? 
Is it always like that or did you manage to start downloading?

**Comment by immotal** [comment]
yes, it is a fresh install? and the downloading button is dark and can not click to download the model 
thank you for response.

**Comment by Saik0s** [comment]
A new version is now available on the App Store that this issue is fixed!
