### ISSUE TITLE
`Tuist` config is missing?

### ISSUE THREAD

**Issue by foxsin10** [Saik0s/Whisperboard#4]
Great work.

But I have some problem on generating the project. Follow the `README.md`, I run `make` command and only get the following on terminal:

```
tuist fetch
make: tuist: No such file or directory
make: *** [all] Error 1
```

Is there something i missed?

**Comment by Saik0s** [comment]
Thanks for pointing. Project file is generated using [tuist](tuist.github.io/tuist/main/documentation/projectdescription/project/) CLI utility that is actually bundled in this repository. 

Right now you can run `sh ci_scripts/ci_post_clone.sh` in the root folder of the project and it will generate workspace and project files. I will update Makefile to use bundled `tuist`.

**Comment by foxsin10** [comment]
Thanks

**Comment by Saik0s** [comment]
@foxsin10 I have just update the repository with a proper Makefile. It should now generate project files from just running `make` in the root folder.

**Comment by foxsin10** [comment]
@Saik0s And the updates of the dependencies, that's very nice!
