### ISSUE TITLE
KeyboardKit_KeyboardKit.bundle: No such file or directory

### ISSUE THREAD

**Issue by binchen1998** [Saik0s/Whisperboard#6]
Hi,

Thanks for your great job. I cloned your code and followed the instructions. After the successfully make, open the xcode, press run. There is an error:

/Users/binchen/Library/Developer/Xcode/DerivedData/WhisperBoard-enonstfmvuacfxcgqzvzabfepqgv/Build/Products/Debug-iphonesimulator/KeyboardKit_KeyboardKit.bundle /Users/binchen/Library/Developer/Xcode/DerivedData/WhisperBoard-enonstfmvuacfxcgqzvzabfepqgv/Build/Products/Debug-iphonesimulator/KeyboardKit_KeyboardKit.bundle: No such file or directory

I checked that 'make' process successfully downloaded the KeyboardKit git repository. How can I work around?

**Comment by Saik0s** [comment]
Hi @binchen1998, I tried to reproduce, made a new clone of the repository, ran `make` and built the project which was successful. I would suggest to do the following:
1. Clean Derived Data `rm -rf ~/Library/Developer/Xcode/DerivedData/*`
2. Run `make` again

**Comment by wangdashuaihenshuai** [comment]
i got the same question. re make but also question exist.

**Comment by Saik0s** [comment]
I will investigate it. I'm likely to get rid of the keyboard extension, since it's not really useful anyway.

**Comment by Saik0s** [comment]
Removed Keyboard extension
