### ISSUE TITLE
Multilingual model translated into English

### ISSUE THREAD

**Issue by IlianP** [Saik0s/Whisperboard#7]
tested on an iPhone 8 with iOS 16.3.1

I chose the "ggml-small.bin" which I thought would be the multilingual model (like the one from Whisper, without the "en" that I had tested before). But when I spoke 3 test sentences in German, in its output, it was translated into English:

"Okay, that's just a test. But I don't know exactly how this transcription should work. Maybe it would be a potential possibility." 

That is indeed a very good translation of what I said in German, but not the task it is supposed to do. :-)

**Comment by Saik0s** [comment]
Hi @IlianP, there is indeed a problem with output language. I am already working on a new feature that would allow user to select their desired output language. Will be available in the next release!

**Comment by Saik0s** [comment]
A new version is now available on the App Store that includes the ability to select a language in the settings. By default, it is set to automatic.
