### ISSUE TITLE
make didn't working 

### ISSUE THREAD

**Issue by ymatsumoto65** [Saik0s/Whisperboard#9]
When I tried to build your project, I got the following error.

make
Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Swift Package Manager dependencies.
error: 'swiftpackagemanager': Invalid manifest
/Path_to/Whisperboard-main/Tuist/Dependencies/SwiftPackageManager/Package.swift:2:8: error: module 'PackageDescription' was created for incompatible target x86_64-apple-macosx10.14: /var/folders/y9/4jvdtw7517q5c3tvz0ttyj2r0000gn/C/clang/ModuleCache/PackageDescription-3QVF8C4290OM5.swiftmodule
import PackageDescription
       ^
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
make: *** [all] Error 1

My swift version is 
Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-darwin22.3.0

How can I modify the settings to build your project?
Thanks in advance.

**Comment by Saik0s** [comment]
Hi @ymatsumoto65, can you try the following steps: 
- Install [tuist](https://github.com/tuist/tuist) 
- run `tuist fetch`
- run `tuist generate`

**Comment by ymatsumoto65** [comment]
Thank you for your reply. I installed tuist and run
`tuist fetch`
Then, I still got the same error...

Resolving and fetching plugins.
Plugins resolved and fetched successfully.
Resolving and fetching dependencies.
Installing Swift Package Manager dependencies.
error: 'swiftpackagemanager': Invalid manifest
/Path_to/Whisperboard-main/Tuist/Dependencies/SwiftPackageManager/Package.swift:2:8: error: module 'PackageDescription' was created for incompatible target x86_64-apple-macosx10.14: /var/folders/y9/4jvdtw7517q5c3tvz0ttyj2r0000gn/C/clang/ModuleCache/PackageDescription-3QVF8C4290OM5.swiftmodule
import PackageDescription
       ^
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

**Comment by Saik0s** [comment]
Can you remove DerivedData and try again? You can use this command `rm -rf ~/Library/Developer/Xcode/DerivedData/*`

**Comment by zurrixxx** [comment]
I have the same error, even after try `rm -rf ~/Library/Developer/Xcode/DerivedData/*`

**Comment by Neilpang** [comment]
same errors for me too.


```
Installing Swift Package Manager dependencies.
error: terminated(1): /usr/bin/xcrun --sdk macosx --show-sdk-platform-path output:
    xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
    xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
    
The 'swift' command exited with error code 1
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose


```

**Comment by Saik0s** [comment]
I am closing this issue, but let me know if someone is still having this problem.
